org: elijahdashdan
app: stream-api
service: stream-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /newtest
          method: get
